name: Build and test
on:
  push:
  pull_request:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: SebRollen/toml-action@v1.0.2
      id: read_rust_toolchain
      with:
        file: rust-toolchain
        field: toolchain.channel
    - uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: ${{ steps.read_rust_toolchain.outputs.value }}
        components: clippy, rustfmt
    - uses: Swatinem/rust-cache@v2
      with:
        prefix-key: possum-build
    - name: Run rustfmt check
      run: cargo fmt --all --check
    - name: Build possum binary (debug)
      run: |-
        mkdir $RUNNER_TEMP/artifacts
        cargo build --bin=possum -Z unstable-options --out-dir=$RUNNER_TEMP/artifacts
      shell: bash
  # - run: sudo apt-get update
  #   shell: bash
  # - run: sudo apt-get install opam libzstd-dev python3-pip
  #   shell: bash
